"""z:coset-reps — which cosets H/L contain a twofold (crystallographic PGs)."""
from __future__ import annotations

import pytest

from helpers import matmul_int, det3

pytestmark = [pytest.mark.zcheck]

I = ((1, 0, 0), (0, 1, 0), (0, 0, 1))


def _as_int_tuple(W):
    return tuple(tuple(int(x) for x in row) for row in W.rows)


def _proper_point_group(sg_number):
    from agentsg.space_groups import space_group
    from agentsg.group import point_group
    rots = point_group(space_group(sg_number).operations())
    out = set()
    for W in rots:
        M = _as_int_tuple(W)
        if det3(M) == 1:
            out.add(M)
    return frozenset(out)


# Proper rotation groups from standard SG numbers
GROUPS = {
    "1": _proper_point_group(1),
    "2": _proper_point_group(3),       # P2
    "222": _proper_point_group(16),    # P222
    "4": _proper_point_group(75),      # P4
    "422": _proper_point_group(89),    # P422
    "3": _proper_point_group(143),     # P3
    "32": _proper_point_group(150),    # P321
    "6": _proper_point_group(168),     # P6
    "622": _proper_point_group(177),   # P622
    "23": _proper_point_group(195),    # P23
    "432": _proper_point_group(207),   # P432
}


def _order_fixed(M):
    P = M
    for k in range(1, 7):
        if P == I:
            return k
        P = matmul_int(P, M)
    return None


def _close(gens):
    G = set(gens) | {I}
    changed = True
    while changed:
        changed = False
        nxt = set()
        for a in G:
            for b in G:
                nxt.add(matmul_int(a, b))
        if not nxt <= G:
            G |= nxt
            changed = True
    return frozenset(G)


def _all_subgroups(H):
    """Subgroups of H generated by at most two elements."""
    els = list(H)
    subs = {frozenset([I])}
    for a in els:
        for b in els:
            S = _close([a, b])
            if S <= H:
                subs.add(S)
    return subs


def _left_cosets(H, G):
    remaining = set(H)
    cosets = []
    while remaining:
        rep = remaining.pop()
        coset = {matmul_int(rep, g) for g in G}
        cosets.append(frozenset(coset))
        remaining -= coset
    return cosets


def _n_cosets_without_twofold(H, G):
    """Count cosets with no order-2 element (identity coset included)."""
    return sum(
        1 for C in _left_cosets(H, G)
        if not any(_order_fixed(x) == 2 for x in C)
    )


def test_group_orders():
    expect = {
        "1": 1, "2": 2, "222": 4, "4": 4, "422": 8,
        "3": 3, "32": 6, "6": 6, "622": 12, "23": 12, "432": 24,
    }
    for name, n in expect.items():
        assert len(GROUPS[name]) == n, f"{name}: |G|={len(GROUPS[name])} != {n}"
        for M in GROUPS[name]:
            assert det3(M) == 1


def test_index2_cosets_always_have_twofold():
    """Every index-2 subgroup: no coset lacks a twofold (observed 0)."""
    for Hn in ("222", "422", "622", "432"):
        H = GROUPS[Hn]
        for G in _all_subgroups(H):
            if len(H) // len(G) != 2:
                continue
            assert _n_cosets_without_twofold(H, G) == 0, (
                f"{Hn} index-2 subgroup had a twofold-free coset"
            )

    # Named index-2 pairs from the manuscript (when G embeds in H)
    pairs = [
        ("222", "2"),
        ("422", "4"),
        ("422", "222"),
        ("622", "6"),
        ("622", "32"),
        ("432", "23"),
    ]
    for Hn, Gn in pairs:
        H, G = GROUPS[Hn], GROUPS[Gn]
        assert G <= H, f"{Gn} not <= {Hn}"
        assert _n_cosets_without_twofold(H, G) == 0

    # 432/4 has index 6 and still has a twofold in every coset
    H, G = GROUPS["432"], GROUPS["4"]
    assert G <= H
    assert len(H) // len(G) == 6
    assert _n_cosets_without_twofold(H, G) == 0


def test_higher_index_cosets_without_twofold_counts():
    """Manuscript observed counts for higher-index (H, G) pairs."""
    # (H name, |G|, expected n cosets with no twofold)
    expect = [
        ("422", 2, 1),   # 422/2 — e.g. {4, 4^3}
        ("622", 3, 1),   # 622/3 — identity coset has no twofold
        ("432", 4, 2),   # 432/222
        ("432", 2, 5),   # 432/2
        ("622", 1, 5),   # 622/1
        ("432", 1, 15),  # 432/1
    ]
    for Hn, order_g, n_without in expect:
        H = GROUPS[Hn]
        hits = [
            G for G in _all_subgroups(H)
            if len(G) == order_g and _n_cosets_without_twofold(H, G) == n_without
        ]
        assert hits, (
            f"{Hn}/|G|={order_g}: no subgroup gives {n_without} twofold-free cosets"
        )
