"""
Allowed origins and structure semi-invariants, as one lattice computation.

An origin shift ``o`` is *allowed* when conjugating the group by ``(I, o)``
leaves the operator set unchanged, i.e.

    (W - I) o  ∈  L        for every rotation part W,

with ``L`` the translation lattice of the group (``Z^3`` plus the centring
vectors). The allowed shifts form a group ``T'`` with ``L ⊆ T'``, and the
structure semi-invariants are the reflections whose phase does not move
under any allowed shift, i.e. the dual lattice ``T'^* = {h : h·t ∈ Z ∀ t ∈ T'}``.

This is the same construction as the reflection conditions in
:mod:`agentsg.reflection_lattice` (present reflections = dual of the lattice
augmented by the screw/glide translations on a stratum), applied to a
different augmentation of ``L``. Everything follows from one Smith normal
form and nothing is sampled on a grid.

**Construction.** Choose a primitive basis ``B`` of ``L`` (rows ``b_j``).
In ``L``-coordinates ``o = Bᵀ c`` every rotation becomes the integer matrix
``A_W = (Bᵀ)⁻¹ (W − I) Bᵀ`` and the condition reads ``A_W c ∈ Z³``. Stack the
``A_W`` for a generating set into ``A`` and take the Smith normal form
``U A V = diag(s₁, s₂, s₃)`` (``U``, ``V`` unimodular). With ``y = V⁻¹ c``:

* ``s_i = 0``  → ``y_i`` is unconstrained: a **floating** origin direction,
  ``v_i`` (column ``i`` of ``V``), pulled back to ``Bᵀ v_i``.
* ``s_i = 1``  → ``y_i ∈ Z``: no freedom beyond ``L``.
* ``s_i > 1``  → ``y_i ∈ (1/s_i) Z``: a cyclic **torsion** (Cheshire) factor
  ``Z/s_i`` generated by the origin shift ``Bᵀ v_i / s_i``.

So ``T' / (L + V_float) ≅ ⊕ Z/s_i``, the number of alternative origins is
``∏ s_i`` over the non-zero invariants, and a reflection ``h`` (in ``L^*``,
i.e. not centring-absent) is a semi-invariant iff ``h · (Bᵀ v_i) = 0`` for
every floating ``i`` and ``h · (Bᵀ v_i / s_i) ∈ Z`` for every torsion ``i``.
Reporting each torsion generator ``o_i`` with denominator ``D_i`` as the
congruence ``(D_i o_i) · h ≡ 0 (mod D_i)`` gives the familiar SgInfo-style
vectors, e.g. ``(1,1,1)|2`` for Fm-3m and ``(1,-1,0)|3`` for P3.
"""
from __future__ import annotations
from dataclasses import dataclass
from fractions import Fraction as Fr
from functools import lru_cache
from itertools import product
from math import gcd, lcm
from typing import Iterable, Sequence

from .linalg import Matrix3, Vector3, IDENTITY3, ZERO3
from .symmetry_op import SymmetryOp
from .group import point_group, centering_translations
from .reflection_lattice import _row_hnf, smith_normal_form, _unimodular_inverse


# --- the origin lattice -------------------------------------------------------------


def _primitive_basis(centering: Sequence[Vector3]) -> Matrix3:
    """Rows are a basis of ``L = Z³ + <centring>`` (row Hermite normal form)."""
    D = 1
    for c in centering:
        for x in c.v:
            D = lcm(D, x.denominator)
    rows = [[D * int(i == j) for j in range(3)] for i in range(3)]
    rows += [[int(x * D) for x in c.v] for c in centering]
    H = _row_hnf(rows)
    return Matrix3([[Fr(x, D) for x in r] for r in H])


@dataclass(frozen=True)
class OriginLattice:
    """Allowed-origin group ``T'`` of a space group, from one Smith normal form.

    ``floating``: integer primitive directions of continuous origin freedom.
    ``torsion``: (generator, order) pairs — origin shifts generating the
    finite part ``T'/(L + V_float) ≅ ⊕ Z/order``, reduced modulo ``L`` and
    with floating components pinned to zero.
    ``centering``: the centring translations of ``L`` (including zero).
    """

    floating: tuple[Vector3, ...]
    torsion: tuple[tuple[Vector3, int], ...]
    centering: tuple[Vector3, ...]
    _Bt: Matrix3          # o = Bᵀ c  (columns of Bᵀ are the primitive basis)
    _Bt_inv: Matrix3
    _V: tuple[tuple[int, ...], ...]      # rows of V; column v_i = generator i
    _V_inv: tuple[tuple[int, ...], ...]
    _s: tuple[int, ...]
    # Smith factor ``U A V = D`` of the stacked ``(W − I)`` blocks in the
    # primitive basis, and the rotation order of those blocks. The Euclidean
    # normalizer reuses this factorization instead of recomputing it.
    _U: tuple[tuple[int, ...], ...] = ()
    _stack_W: tuple[Matrix3, ...] = ()

    @property
    def n_alternative_origins(self) -> int:
        """Number of discrete alternative origins (index of ``L + V`` in ``T'``)."""
        n = 1
        for _, k in self.torsion:
            n *= k
        return n

    @property
    def invariant_factors(self) -> tuple[int, ...]:
        """Orders of the cyclic torsion factors (each divides the next)."""
        return tuple(k for _, k in self.torsion)

    # -- coordinate helpers --------------------------------------------------------

    def _y(self, o: Vector3) -> Vector3:
        """Smith coordinates ``y = V⁻¹ (Bᵀ)⁻¹ o``."""
        c = self._Bt_inv @ o
        return Vector3(
            sum(self._V_inv[i][k] * c.v[k] for k in range(3)) for i in range(3)
        )

    def _from_y(self, y: Sequence[Fr]) -> Vector3:
        c = Vector3(sum(self._V[k][i] * y[i] for i in range(3)) for k in range(3))
        return self._Bt @ c

    def pin(self, o: Vector3) -> Vector3:
        """Drop the floating components of ``o`` (exact, any direction)."""
        y = list(self._y(o).v)
        for i, s in enumerate(self._s):
            if s == 0:
                y[i] = Fr(0)
        return self._from_y(y)

    def reduce(self, o: Vector3) -> Vector3:
        """Canonical representative of ``o`` modulo ``L`` and floating shifts."""
        p = self.pin(o).mod1()
        return min(((p + c).mod1() for c in self.centering), key=lambda v: v.v)

    def is_allowed(self, o: Vector3) -> bool:
        """True iff ``o ∈ T'`` (i.e. ``(W − I) o ∈ L`` for all W)."""
        y = self._y(o)
        return all(
            (y.v[i] * s).denominator == 1 for i, s in enumerate(self._s) if s != 0
        )

    def discrete_origins(self) -> list[Vector3]:
        """All discrete alternative origins: ``T'/(L + V_float)``, canonical reps."""
        gens = [(o, k) for o, k in self.torsion]
        out: list[Vector3] = []
        seen: set = set()
        for ks in product(*[range(k) for _, k in gens]) if gens else [()]:
            o = ZERO3
            for (g, _), k in zip(gens, ks):
                o = o + Vector3(k * x for x in g.v)
            r = self.reduce(o)
            if r.v not in seen:
                seen.add(r.v)
                out.append(r)
        return sorted(out, key=lambda v: v.v)


def _integer_matrix(M: Matrix3) -> list[list[int]]:
    assert all(x.denominator == 1 for row in M.rows for x in row), M
    return [[int(x) for x in row] for row in M.rows]


def _primitive_int_direction(v: Vector3) -> Vector3:
    D = 1
    for x in v.v:
        D = lcm(D, x.denominator)
    iv = [int(x * D) for x in v.v]
    g = 0
    for x in iv:
        g = gcd(g, abs(x))
    iv = [x // g for x in iv]
    first = next(x for x in iv if x)
    if first < 0:
        iv = [-x for x in iv]
    return Vector3(iv)


def origin_lattice(operations: Iterable[SymmetryOp]) -> OriginLattice:
    """Compute the allowed-origin group ``T'`` of ``operations`` (see module doc)."""
    ops = list(operations)
    return _origin_lattice_cached(tuple(sorted(ops, key=lambda op: (op.W.rows, op.w.v))))


@lru_cache(maxsize=None)
def _origin_lattice_cached(ops: tuple[SymmetryOp, ...]) -> OriginLattice:
    centering = sorted(centering_translations(ops), key=lambda v: v.v)
    B = _primitive_basis(centering)
    Bt = B.transpose()
    Bt_inv = Bt.inverse()
    rotations = [W for W in point_group(ops) if W != IDENTITY3]

    if rotations:
        A: list[list[int]] = []
        for W in rotations:
            AW = _integer_matrix(Bt_inv @ _WmI(W) @ Bt)
            A.extend(AW)
        U, s, V = smith_normal_form(A)
    else:
        U = []
        s, V = [0, 0, 0], [[int(i == j) for j in range(3)] for i in range(3)]
    s = list(s) + [0] * (3 - len(s))
    V_inv = _unimodular_inverse(V)
    Vt = tuple(tuple(r) for r in V)
    Vi = tuple(tuple(r) for r in V_inv)
    Ut = tuple(tuple(int(x) for x in row) for row in U)
    stack_W = tuple(rotations)

    lat = OriginLattice(
        floating=(), torsion=(), centering=tuple(centering),
        _Bt=Bt, _Bt_inv=Bt_inv, _V=Vt, _V_inv=Vi, _s=tuple(s),
        _U=Ut, _stack_W=stack_W,
    )

    # Floating directions: pull back kernel columns, then HNF for a canonical
    # (axis-aligned where possible) integer basis.
    float_rows = []
    for i, si in enumerate(s):
        if si == 0:
            d = _primitive_int_direction(lat._from_y([Fr(int(j == i)) for j in range(3)]))
            float_rows.append([int(x) for x in d.v])
    floating = tuple(
        _primitive_int_direction(Vector3(r)) for r in _row_hnf(float_rows)
    ) if float_rows else ()

    torsion = []
    for i, si in enumerate(s):
        if si > 1:
            g = lat._from_y([Fr(int(j == i), si) for j in range(3)])
            torsion.append((_nicest_generator(g, si, lat), si))

    return OriginLattice(
        floating=floating, torsion=tuple(torsion), centering=tuple(centering),
        _Bt=Bt, _Bt_inv=Bt_inv, _V=Vt, _V_inv=Vi, _s=tuple(s),
        _U=Ut, _stack_W=stack_W,
    )


def _nicest_generator(g: Vector3, order: int, lat: OriginLattice) -> Vector3:
    """Among the generators ``k g`` (gcd(k, order) = 1) of one cyclic factor and
    their coset representatives modulo ``L``, pick the one whose congruence
    vector is smallest (fewest/smallest entries, non-negative preferred)."""
    best = None
    for k in range(1, order):
        if gcd(k, order) != 1:
            continue
        kg = lat.pin(Vector3(k * x for x in g.v)).mod1()
        for c in lat.centering:
            cand = (kg + c).mod1()
            si = _congruence(cand)
            key = (sum(abs(x) for x in si.vector), sum(x < 0 for x in si.vector),
                   si.vector, cand.v)
            if best is None or key < best[0]:
                best = (key, cand)
    assert best is not None
    return best[1]


def _WmI(W: Matrix3) -> Matrix3:
    """Compute (W - I) as an exact Matrix3."""
    return Matrix3([
        [W.rows[i][j] - (1 if i == j else 0) for j in range(3)]
        for i in range(3)
    ])


# --- public API (names kept for identify.py / asu.py) --------------------------------


def floating_origin_basis(operations: Iterable[SymmetryOp]) -> tuple[Vector3, ...]:
    """Integer basis of the continuous (floating) origin freedom.

    Empty for groups with a unique origin (P222, P23, …), length 1 for polar
    unique-axis groups (P2, P4, P3, P6, …), length 3 for P1.
    """
    return origin_lattice(operations).floating


def pin_floating_origin(p: Vector3, operations: Iterable[SymmetryOp]) -> Vector3:
    """Canonical gauge: remove the floating-origin components of ``p`` exactly."""
    return origin_lattice(operations).pin(p).mod1()


def is_allowed_origin(o: Vector3, operations: Iterable[SymmetryOp]) -> bool:
    """True if conjugating the group by origin ``o`` leaves the operator set unchanged."""
    return origin_lattice(operations).is_allowed(o)


def discrete_allowed_origins(operations: Sequence[SymmetryOp]) -> list[Vector3]:
    """The distinct alternative origins ``T'/(L + V_float)``.

    Each is reduced modulo the centring translations and has its floating
    components pinned to zero, so e.g. Fm-3m gives ``[(0,0,0), (0,0,1/2)]``
    (``(1/2,1/2,1/2)`` is the same origin plus an F translation) and Im-3m
    gives ``[(0,0,0)]`` only.
    """
    return origin_lattice(operations).discrete_origins()


_discrete_allowed_origins = discrete_allowed_origins  # back-compat alias


def n_alternative_origins(operations: Iterable[SymmetryOp]) -> int:
    """Number of discrete alternative origins (∏ of the invariant factors)."""
    return origin_lattice(operations).n_alternative_origins


@dataclass(frozen=True)
class SemiInvariant:
    """One structure-semi-invariant congruence ``vector · h ≡ 0 (mod modulus)``.

    ``modulus == 0`` means the linear form must vanish exactly (continuous
    origin freedom along that direction).
    """

    vector: tuple[int, int, int]
    modulus: int

    def accepts(self, h: int, k: int, l: int) -> bool:
        """True if reflection (h, k, l) satisfies the congruence."""
        u = self.vector[0] * h + self.vector[1] * k + self.vector[2] * l
        if self.modulus == 0:
            return u == 0
        return u % self.modulus == 0


def _congruence(o: Vector3) -> SemiInvariant:
    """``h · o ∈ Z``  as  ``(D o) · h ≡ 0 (mod D)`` with entries in (−D/2, D/2]."""
    D = 1
    for x in o.v:
        D = lcm(D, x.denominator)
    iv = []
    for x in o.v:
        a = int(x * D) % D
        if a > D // 2:
            a -= D
        iv.append(a)
    first = next((x for x in iv if x), 0)
    if first < 0:
        iv = [-x for x in iv]
    return SemiInvariant((iv[0], iv[1], iv[2]), D)


def semi_invariants(operations: Iterable[SymmetryOp]) -> list[SemiInvariant]:
    """Structure semi-invariant congruences, derived from the origin lattice.

    Stated on reflections that are not centring-absent (``h ∈ L^*``), as in
    SgInfo. One modulus-``D`` congruence per torsion generator, one modulus-0
    constraint per floating direction.
    """
    lat = origin_lattice(operations)
    out = [_congruence(o) for o, _ in lat.torsion]
    for v in lat.floating:
        out.append(SemiInvariant(tuple(int(x) for x in v.v), 0))  # type: ignore[arg-type]
    return out


def is_semi_invariant(hkl: Vector3 | tuple, operations: Iterable[SymmetryOp]) -> bool:
    """True if ``hkl`` is a structure semi-invariant: ``h · t ∈ Z`` for all ``t ∈ T'``.

    Includes the centring translations, so a centring-absent reflection is
    never a semi-invariant.
    """
    if isinstance(hkl, Vector3):
        if any(x.denominator != 1 for x in hkl.v):
            raise ValueError("hkl must be integral")
        h = hkl
    else:
        h = Vector3(tuple(int(x) for x in hkl))
    lat = origin_lattice(operations)
    if any(h.dot(c).denominator != 1 for c in lat.centering):
        return False
    if any(h.dot(v) != 0 for v in lat.floating):
        return False
    return all(h.dot(o).denominator == 1 for o, _ in lat.torsion)
